/// Golden Rules enforcement tests — generated by spine-rules.
///
/// These tests enforce spine protocol invariants from GOLDEN_RULES.md.
/// Each test name references a rule ID (R-001, R-007, etc.) so violations
/// are traceable to the specification.
use spine_rules::golden_rules_suite;

golden_rules_suite! {
    binary: env!("CARGO_BIN_EXE_canon"),
    operator_json: include_str!("../operator.json"),
    source_files: &["src/lib.rs", "src/refusal.rs"],
    fixture_success_args: &[
        "tests/fixtures/inputs/all_resolved.csv",
        "--registry", "tests/fixtures/registries/cusip-isin",
        "--column", "cusip", "--no-witness",
    ],
    fixture_refusal_args: &[
        "nonexistent.csv",
        "--registry", "tests/fixtures/registries/cusip-isin",
        "--column", "cusip", "--no-witness",
    ],
    fixture_csv: "tests/fixtures/inputs/partial.csv",
    fixture_csv_args: &[
        "tests/fixtures/inputs/partial.csv",
        "--registry", "tests/fixtures/registries/cusip-isin",
        "--column", "cusip", "--emit", "csv", "--no-witness",
    ],
}
