#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum MutationClass {
    ReadOnly,
    OwnedOutput,
    CacheOnly,
    RegistryMutation,
    PublicationTransaction,
    ExternalMaterialization,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum NetworkClass {
    Offline,
    DeniedByDefault,
    ExplicitExternalProvider,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ConcurrencyClass {
    StatelessRead,
    AtomicOwnedOutput,
    CacheRaceSafe,
    ExclusiveRegistryMutation,
    OptimisticPublicationCas,
    IsolatedRunner,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum PlatformClass {
    PortablePathUtf8,
    SameFilesystemAtomicReplace,
    UnixPermissionBits,
    RejectLinks,
    AdvisoryFileLock,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CommandSafetyDeclaration {
    pub command: &'static str,
    pub operator_contract_name: Option<&'static str>,
    pub usage: &'static str,
    pub read_only: bool,
    pub mutation: MutationClass,
    pub network: NetworkClass,
    pub concurrency: ConcurrencyClass,
    pub platforms: &'static [PlatformClass],
    pub owned_temp_fixtures_only: bool,
    pub notes: &'static str,
}

pub const SAFETY_MATRIX_SCHEMA_VERSION: &str = "canon.operator.safety_matrix.v1";

pub const CORE_PLATFORM_CLASSES: &[PlatformClass] = &[
    PlatformClass::PortablePathUtf8,
    PlatformClass::SameFilesystemAtomicReplace,
    PlatformClass::UnixPermissionBits,
    PlatformClass::RejectLinks,
    PlatformClass::AdvisoryFileLock,
];

pub const COMMAND_SAFETY_DECLARATIONS: &[CommandSafetyDeclaration] = &[
    CommandSafetyDeclaration {
        command: "doctor",
        operator_contract_name: Some("doctor"),
        usage: "canon doctor [health --json|capabilities --json|robot-docs|--robot-triage]",
        read_only: true,
        mutation: MutationClass::ReadOnly,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::StatelessRead,
        platforms: &[PlatformClass::PortablePathUtf8],
        owned_temp_fixtures_only: true,
        notes: "operator contract inspection only; no fixers or writes",
    },
    CommandSafetyDeclaration {
        command: "lookup",
        operator_contract_name: None,
        usage: "canon <INPUT> --registry <DIR> --column <COL> --no-witness",
        read_only: true,
        mutation: MutationClass::ReadOnly,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::StatelessRead,
        platforms: &[PlatformClass::PortablePathUtf8],
        owned_temp_fixtures_only: true,
        notes: "exact lookup reads input and registry; safety harness disables witness and registry index cache",
    },
    CommandSafetyDeclaration {
        command: "package inspect",
        operator_contract_name: Some("package inspect"),
        usage: "canon package inspect <ARCHIVE>",
        read_only: true,
        mutation: MutationClass::ReadOnly,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::StatelessRead,
        platforms: &[PlatformClass::PortablePathUtf8, PlatformClass::RejectLinks],
        owned_temp_fixtures_only: true,
        notes: "local archive read only",
    },
    CommandSafetyDeclaration {
        command: "package verify",
        operator_contract_name: Some("package verify"),
        usage: "canon package verify <ARCHIVE>",
        read_only: true,
        mutation: MutationClass::ReadOnly,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::StatelessRead,
        platforms: &[PlatformClass::PortablePathUtf8, PlatformClass::RejectLinks],
        owned_temp_fixtures_only: true,
        notes: "local archive digest and contract verification only",
    },
    CommandSafetyDeclaration {
        command: "package pack",
        operator_contract_name: Some("package pack"),
        usage: "canon package pack --root <DIR> --package <package.json> --out <ARCHIVE>",
        read_only: false,
        mutation: MutationClass::OwnedOutput,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::AtomicOwnedOutput,
        platforms: &[
            PlatformClass::PortablePathUtf8,
            PlatformClass::SameFilesystemAtomicReplace,
            PlatformClass::UnixPermissionBits,
            PlatformClass::RejectLinks,
        ],
        owned_temp_fixtures_only: true,
        notes: "writes a declared archive path only",
    },
    CommandSafetyDeclaration {
        command: "package unpack",
        operator_contract_name: Some("package unpack"),
        usage: "canon package unpack <ARCHIVE> --target <EMPTY_DIR>",
        read_only: false,
        mutation: MutationClass::OwnedOutput,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::AtomicOwnedOutput,
        platforms: &[PlatformClass::PortablePathUtf8, PlatformClass::RejectLinks],
        owned_temp_fixtures_only: true,
        notes: "writes only inside an explicit existing empty target directory",
    },
    CommandSafetyDeclaration {
        command: "registry lint",
        operator_contract_name: Some("registry lint"),
        usage: "canon registry lint <DIR> --emit json",
        read_only: true,
        mutation: MutationClass::ReadOnly,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::StatelessRead,
        platforms: &[PlatformClass::PortablePathUtf8],
        owned_temp_fixtures_only: true,
        notes: "registry health inspection",
    },
    CommandSafetyDeclaration {
        command: "registry providers",
        operator_contract_name: Some("registry providers"),
        usage: "canon registry providers --emit json",
        read_only: true,
        mutation: MutationClass::ReadOnly,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::StatelessRead,
        platforms: &[PlatformClass::PortablePathUtf8],
        owned_temp_fixtures_only: true,
        notes: "provider catalog is generated locally and must not contact providers",
    },
    CommandSafetyDeclaration {
        command: "registry index cache",
        operator_contract_name: None,
        usage: "managed registry index cache under ~/.cmdrvl/cache/registry-indexes",
        read_only: false,
        mutation: MutationClass::CacheOnly,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::CacheRaceSafe,
        platforms: &[
            PlatformClass::PortablePathUtf8,
            PlatformClass::SameFilesystemAtomicReplace,
        ],
        owned_temp_fixtures_only: true,
        notes: "cache writes are optional, derived, disableable with CANON_REGISTRY_INDEX_MODE=no-cache, and never source of truth",
    },
    CommandSafetyDeclaration {
        command: "registry provider-schema",
        operator_contract_name: Some("registry provider-schema"),
        usage: "canon registry provider-schema <PROVIDER> --emit json",
        read_only: true,
        mutation: MutationClass::ReadOnly,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::StatelessRead,
        platforms: &[PlatformClass::PortablePathUtf8],
        owned_temp_fixtures_only: true,
        notes: "provider schema is generated locally and must not contact providers",
    },
    CommandSafetyDeclaration {
        command: "registry export",
        operator_contract_name: Some("registry export"),
        usage: "canon registry export --format dbt-seed --registry <DIR> --out <PATH>",
        read_only: false,
        mutation: MutationClass::OwnedOutput,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::AtomicOwnedOutput,
        platforms: &[
            PlatformClass::PortablePathUtf8,
            PlatformClass::SameFilesystemAtomicReplace,
        ],
        owned_temp_fixtures_only: true,
        notes: "writes declared export artifacts without mutating registry inputs",
    },
    CommandSafetyDeclaration {
        command: "registry build mock",
        operator_contract_name: Some("registry build"),
        usage: "canon registry build --source mock --seed <CSV> --output <DIR>",
        read_only: false,
        mutation: MutationClass::ExternalMaterialization,
        network: NetworkClass::DeniedByDefault,
        concurrency: ConcurrencyClass::AtomicOwnedOutput,
        platforms: &[
            PlatformClass::PortablePathUtf8,
            PlatformClass::SameFilesystemAtomicReplace,
        ],
        owned_temp_fixtures_only: true,
        notes: "mock provider materializes from local seed data and is the only offline build case",
    },
    CommandSafetyDeclaration {
        command: "registry build openfigi",
        operator_contract_name: Some("registry build"),
        usage: "canon registry build --source openfigi --seed <CSV> --output <DIR>",
        read_only: false,
        mutation: MutationClass::ExternalMaterialization,
        network: NetworkClass::ExplicitExternalProvider,
        concurrency: ConcurrencyClass::AtomicOwnedOutput,
        platforms: &[
            PlatformClass::PortablePathUtf8,
            PlatformClass::SameFilesystemAtomicReplace,
        ],
        owned_temp_fixtures_only: true,
        notes: "external provider access is opt-in and must be refused by offline harnesses before spawn",
    },
    CommandSafetyDeclaration {
        command: "registry mutation",
        operator_contract_name: Some("registry add-entry"),
        usage: "canon registry add-entry|mint|default-id-scheme --registry <DIR> ...",
        read_only: false,
        mutation: MutationClass::RegistryMutation,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::ExclusiveRegistryMutation,
        platforms: &[
            PlatformClass::PortablePathUtf8,
            PlatformClass::SameFilesystemAtomicReplace,
        ],
        owned_temp_fixtures_only: true,
        notes: "registry mutations require explicit registry roots and version movement",
    },
    CommandSafetyDeclaration {
        command: "strategy read",
        operator_contract_name: Some("strategy explain"),
        usage: "canon strategy list|explain|resolve ...",
        read_only: true,
        mutation: MutationClass::ReadOnly,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::StatelessRead,
        platforms: &[PlatformClass::PortablePathUtf8],
        owned_temp_fixtures_only: true,
        notes: "strategy resolution and explanation do not execute scripts",
    },
    CommandSafetyDeclaration {
        command: "strategy audit",
        operator_contract_name: Some("strategy audit"),
        usage: "canon strategy audit --schema <PROFILE.json> --script <SCRIPT> --suite <DIR>",
        read_only: true,
        mutation: MutationClass::ReadOnly,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::IsolatedRunner,
        platforms: &[
            PlatformClass::PortablePathUtf8,
            PlatformClass::UnixPermissionBits,
        ],
        owned_temp_fixtures_only: true,
        notes: "runs inside an isolated runner with denied network and scratch-only writes",
    },
    CommandSafetyDeclaration {
        command: "strategy mutation",
        operator_contract_name: Some("strategy promote"),
        usage: "canon strategy register|update|deprecate|promote --registry <DIR> ...",
        read_only: false,
        mutation: MutationClass::RegistryMutation,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::ExclusiveRegistryMutation,
        platforms: &[
            PlatformClass::PortablePathUtf8,
            PlatformClass::SameFilesystemAtomicReplace,
        ],
        owned_temp_fixtures_only: true,
        notes: "mutates strategy registry entries and may append witness unless disabled",
    },
    CommandSafetyDeclaration {
        command: "entity read",
        operator_contract_name: Some("entity explain"),
        usage: "canon entity explain|review export ...",
        read_only: true,
        mutation: MutationClass::ReadOnly,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::StatelessRead,
        platforms: &[PlatformClass::PortablePathUtf8],
        owned_temp_fixtures_only: true,
        notes: "artifact explanation and review export read immutable result artifacts",
    },
    CommandSafetyDeclaration {
        command: "entity workbench",
        operator_contract_name: Some("entity run"),
        usage: "canon entity run|block|evidence|solve|audit --no-witness ...",
        read_only: false,
        mutation: MutationClass::OwnedOutput,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::CacheRaceSafe,
        platforms: &[
            PlatformClass::PortablePathUtf8,
            PlatformClass::SameFilesystemAtomicReplace,
        ],
        owned_temp_fixtures_only: true,
        notes: "owned cache/artifact writes only; safety harness disables witness for read checks",
    },
    CommandSafetyDeclaration {
        command: "entity promotion",
        operator_contract_name: Some("entity promote"),
        usage: "canon entity promote|review import --registry <DIR> ...",
        read_only: false,
        mutation: MutationClass::RegistryMutation,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::ExclusiveRegistryMutation,
        platforms: &[
            PlatformClass::PortablePathUtf8,
            PlatformClass::SameFilesystemAtomicReplace,
        ],
        owned_temp_fixtures_only: true,
        notes: "promotion writes registry and sidecars only after audit/profile gates",
    },
    CommandSafetyDeclaration {
        command: "project read",
        operator_contract_name: None,
        usage: "project manifest/lock/plan/explain read",
        read_only: true,
        mutation: MutationClass::ReadOnly,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::StatelessRead,
        platforms: &[PlatformClass::PortablePathUtf8],
        owned_temp_fixtures_only: true,
        notes: "project metadata readers must not create caches or migration files",
    },
    CommandSafetyDeclaration {
        command: "unresolved inbox read",
        operator_contract_name: None,
        usage: "unresolved inbox artifact merge/export/read",
        read_only: true,
        mutation: MutationClass::ReadOnly,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::StatelessRead,
        platforms: &[PlatformClass::PortablePathUtf8],
        owned_temp_fixtures_only: true,
        notes: "inbox artifacts are read or transformed to stdout, not shadow registries",
    },
    CommandSafetyDeclaration {
        command: "inbox read cli",
        operator_contract_name: Some("inbox list"),
        usage: "canon inbox list|show|explain|stats --inbox <INBOX.json>",
        read_only: true,
        mutation: MutationClass::ReadOnly,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::StatelessRead,
        platforms: &[PlatformClass::PortablePathUtf8],
        owned_temp_fixtures_only: true,
        notes: "reads finalized unresolved inbox artifacts and emits ranked JSON/summary only",
    },
    CommandSafetyDeclaration {
        command: "inbox review export",
        operator_contract_name: Some("inbox export-review"),
        usage: "canon inbox export-review --inbox <INBOX.json> [--out <REVIEW.json>]",
        read_only: false,
        mutation: MutationClass::OwnedOutput,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::AtomicOwnedOutput,
        platforms: &[
            PlatformClass::PortablePathUtf8,
            PlatformClass::SameFilesystemAtomicReplace,
        ],
        owned_temp_fixtures_only: true,
        notes: "writes only an explicit review output path when --out is supplied; stdout otherwise",
    },
    CommandSafetyDeclaration {
        command: "inbox review apply",
        operator_contract_name: Some("inbox apply-review"),
        usage: "canon inbox apply-review --inbox <INBOX.json> --review <REVIEW.json> --expected-inbox-hash <HASH> --out <GROUPS.json>",
        read_only: false,
        mutation: MutationClass::OwnedOutput,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::AtomicOwnedOutput,
        platforms: &[
            PlatformClass::PortablePathUtf8,
            PlatformClass::SameFilesystemAtomicReplace,
        ],
        owned_temp_fixtures_only: true,
        notes: "requires explicit inbox hash and writes grouped unresolved artifact to a create-new output path",
    },
    CommandSafetyDeclaration {
        command: "inbox entity plan",
        operator_contract_name: Some("inbox plan-entity"),
        usage: "canon inbox plan-entity --inbox <INBOX.json> --expected-inbox-hash <HASH> --out <REQUEST.json>",
        read_only: false,
        mutation: MutationClass::OwnedOutput,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::AtomicOwnedOutput,
        platforms: &[
            PlatformClass::PortablePathUtf8,
            PlatformClass::SameFilesystemAtomicReplace,
        ],
        owned_temp_fixtures_only: true,
        notes: "plans a bounded entity workbench request without selecting canonical identity",
    },
    CommandSafetyDeclaration {
        command: "publication backend",
        operator_contract_name: None,
        usage: "filesystem publication backend publish/read/current_head",
        read_only: false,
        mutation: MutationClass::PublicationTransaction,
        network: NetworkClass::Offline,
        concurrency: ConcurrencyClass::OptimisticPublicationCas,
        platforms: &[
            PlatformClass::PortablePathUtf8,
            PlatformClass::SameFilesystemAtomicReplace,
            PlatformClass::AdvisoryFileLock,
        ],
        owned_temp_fixtures_only: true,
        notes: "immutable object create-if-absent followed by channel compare-and-swap",
    },
];

pub fn declaration_for(command: &str) -> Option<&'static CommandSafetyDeclaration> {
    COMMAND_SAFETY_DECLARATIONS
        .iter()
        .find(|declaration| declaration.command == command)
}
